// Observation assembler: the byte-exact on-board twin of walker_env._obs().
//
// The layout, joint count and command width all come from obs_spec.h, which is
// GENERATED by tools/gen_obs_spec.py from the deployed run's config + MJCF --
// never hand-edited. tools/gen_obs_vectors.py then freezes real _obs() outputs
// into host/vectors/obs_vectors.h, so a layout drift is a red test rather than
// a robot that walks into a wall.
//
// The frame (deployed loco_v5t spec, 10-DOF v3yaw plant, ext_cmd):
//   [ q(10) | dq(10) | up(3) | linvel(3) | gyro(3) | prev_action(10)
//     | height(1) | sin,cos(2) | cmd(7) ]  = 49 floats
// and the policy sees kHistLen of those, newest first: obs = [f_t, f_t-1, f_t-2].
//
// linvel and height are ZERO on hardware: the training config sets imu_obs=1
// because the robot has no sensor for torso linear velocity or height. The
// generator asserts that, so this cannot silently become wrong.
#pragma once
#include <stddef.h>
#include <stdint.h>

#include "obs/obs_spec.h"

namespace obs {

// Everything the control loop must supply per tick.
struct Inputs {
    float q[kNumJoints];             // joint angles, rad, sim sign convention
    float dq[kNumJoints];            // joint velocities, rad/s
    float up[3];                     // torso up-vector, body frame (from IMU)
    float gyro[3];                   // torso angular velocity, rad/s
    float prev_action[kActDim];      // last action, [-1, 1]
    float phase;                     // gait-clock phase, rad
    float cmd[kNumCmd];              // command channels
};

// Write one kFrameDim-wide observation frame.
void assembleFrame(const Inputs& in, float* out);

// The kHistLen-deep frame ring. Semantics copied from walker_env: the obs
// handed to the policy at tick t is [f_t, f_{t-1}, ..., f_{t-H+1}], and the
// history is updated AFTER the policy has been fed.
class History {
  public:
    // Reset: every history slot becomes `frame` (walker_env does the same on
    // env.reset(), so the first tick is not fed a ring of zeros).
    void fill(const float* frame);
    // Build the full observation from the current frame plus the ring.
    void build(const float* frame, float* obs) const;
    // Push the frame that was just used; drops the oldest.
    void push(const float* frame);

  private:
    // kHistLen - 1 previous frames, newest first.
    float prev_[(kHistLen > 1 ? kHistLen - 1 : 1)][kFrameDim] = {};
};

// The gait clock walker_env advances on-board:
//   phase = wrap_pi(phase + 2*pi*dt*freq)
// Deployed frequency is an open question (docs/firmware-design.md section 8):
// training draws it uniformly from [1.25, 1.75] Hz per episode, so 1.5 Hz is
// the distribution's centre and the v1 default.
class GaitClock {
  public:
    explicit GaitClock(float hz = 1.5f) : freq_(hz) {}
    void advance(float dt);
    void setFrequency(float hz) { freq_ = hz; }
    float phase() const { return phase_; }
    void setPhase(float p) { phase_ = p; }

  private:
    float phase_ = 0.0f;
    float freq_;
};

}  // namespace obs
