// GENERATED by tools/gen_obs_spec.py -- do not edit.
// Source: sim/runs/loco_v5t/config.json + sim/bimo_biped_v3yaw.xml
//
// The observation layout the deployed policy was trained against. Any
// retrain that changes joint count, command width or history depth
// regenerates this file; nothing downstream hardcodes 10 or 49.
#pragma once
#include <stdint.h>

namespace obs {

// -- deployed run ------------------------------------------------------
inline constexpr const char* kRunName = "loco_v5t";
inline constexpr const char* kPlantXml = "bimo_biped_v3yaw.xml";
inline constexpr const char* kActionMap = "full";
inline constexpr bool kImuObs = true;   // linvel + height are zeroed
inline constexpr bool kGaitClock = true;
inline constexpr float kControlDt = 0.02f;   // 50 Hz tick

// -- dimensions --------------------------------------------------------
inline constexpr int kNumJoints = 10;
inline constexpr int kActDim = 10;
inline constexpr int kNumCmd = 7;
inline constexpr int kHistLen = 3;
inline constexpr int kFrameDim = 49;
inline constexpr int kObsDim = 147;

// -- frame layout (offsets into one kFrameDim-wide frame) --------------
inline constexpr int kOffQ = 0;   // 10 wide
inline constexpr int kOffDq = 10;   // 10 wide
inline constexpr int kOffUp = 20;   // 3 wide
inline constexpr int kOffLinVel = 23;   // 3 wide
inline constexpr int kOffGyro = 26;   // 3 wide
inline constexpr int kOffPrevAction = 29;   // 10 wide
inline constexpr int kOffHeight = 39;   // 1 wide
inline constexpr int kOffPhase = 40;   // 2 wide
inline constexpr int kOffCmd = 42;   // 7 wide

// -- joints ------------------------------------------------------------
// Index == the policy's action index == the sim's actuator order
// (joint-tree / qpos-address order). kServoId maps it onto the bus IDs
// from docs/wiring.md -- a real permutation on the 10-DOF plant, since
// the yaw servos were appended as 9/10 after IDs 1-8 were assigned.
inline constexpr const char* kJointNames[kNumJoints] = {"L_hip_yaw", "L_hip_roll", "L_hip_pitch", "L_knee", "L_ankle", "R_hip_yaw", "R_hip_roll", "R_hip_pitch", "R_knee", "R_ankle"};
inline constexpr uint8_t kServoId[kNumJoints] = {10, 1, 2, 3, 4, 9, 5, 6, 7, 8};
inline constexpr float kJointLo[kNumJoints] = {-0.785398163f, -0.436332313f, -1.91986218f, -1.65806279f, -0.698131701f, -0.785398163f, -0.436332313f, -1.91986218f, -1.65806279f, -0.698131701f};
inline constexpr float kJointHi[kNumJoints] = {0.785398163f, 0.436332313f, 1.04719755f, 0.0872664626f, 0.698131701f, 0.785398163f, 0.436332313f, 1.04719755f, 0.0872664626f, 0.698131701f};
inline constexpr float kJointDefault[kNumJoints] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};

}  // namespace obs
