#!/usr/bin/env python3
"""Generate the firmware's policy weights header + forward-pass golden vectors.

Run:  .venv/bin/python tools/gen_policy_weights.py

WHAT THIS IS NOT: the real policy export. sim/export_policy.py (firmware-design
section 7 step 1) does not exist yet, and the deployed net is a (512, 256, 128)
brax MLP -- ~232k params, ~930 KB fp32, which does NOT fit WROOM SRAM without
the distillation decided in firmware-design section 6. That is the v2 seam.

WHAT THIS IS: a PLACEHOLDER net at the real input/output widths (kObsDim ->
... -> 2 * kActDim), plus obs->action pairs computed here in numpy with the
exact brax semantics the firmware must reproduce:

    x       = (obs - mean) / std              running_statistics.normalize
    h_i     = swish(h_{i-1} @ W_i + b_i)      linen.swish, NOT tanh
    logits  = h_n @ W_out + b_out             linear, 2 * action_size wide
    action  = tanh(logits[:action_size])      NormalTanhDistribution.mode()

so firmware/host/test_policy.cpp is a real test of a real forward pass. When
export_policy.py lands it writes the same header shape with real numbers and
these vectors are replaced by JAX's own -- the C side does not change.

Kernel layout is flax's (in, out) row-major, copied verbatim, so the export
never has to transpose.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

WEIGHTS_OUT = os.path.join(ROOT, "firmware", "components", "policy", "include",
                           "policy", "weights.h")
VEC_OUT = os.path.join(ROOT, "firmware", "host", "vectors",
                       "policy_vectors.h")

SPEC_H = os.path.join(ROOT, "firmware", "components", "obs", "include", "obs",
                      "obs_spec.h")

# Placeholder hidden sizes. Small on purpose: the header is committed, and a
# real (512, 256, 128) net would be a megabyte of source. The real net arrives
# distilled (firmware-design section 6) via export_policy.py.
HIDDEN = (32, 32)


def spec_dims():
    """Read kObsDim / kActDim out of the generated obs spec so the two headers
    cannot disagree."""
    txt = open(SPEC_H).read()
    out = {}
    for key in ("kObsDim", "kActDim"):
        for line in txt.splitlines():
            if line.startswith("inline constexpr int %s " % key):
                out[key] = int(line.split("=")[1].strip().rstrip(";"))
    if len(out) != 2:
        raise SystemExit("could not read dims from %s -- run "
                         "tools/gen_obs_spec.py first" % SPEC_H)
    return out["kObsDim"], out["kActDim"]


def fl(x):
    s = "%.9g" % float(x)
    if not any(c in s for c in ".eEn"):
        s += ".0"
    return s + "f"


def carr(name, v, per_line=8):
    v = np.ravel(v)
    lines = ["inline constexpr float %s[%d] = {" % (name, v.size)]
    for i in range(0, v.size, per_line):
        lines.append("    " + ", ".join(fl(x) for x in v[i:i + per_line]) + ",")
    lines.append("};")
    return lines


def swish(x):
    return x / (1.0 + np.exp(-x))


def main():
    obs_dim, act_dim = spec_dims()
    rng = np.random.default_rng(20260726)

    # Plausible-looking normaliser: non-unit scales so a firmware that forgets
    # to normalise fails loudly rather than "nearly passing".
    mean = rng.uniform(-0.5, 0.5, obs_dim).astype(np.float32)
    std = rng.uniform(0.2, 1.8, obs_dim).astype(np.float32)

    sizes = [obs_dim] + list(HIDDEN) + [2 * act_dim]
    layers = []
    for i in range(len(sizes) - 1):
        lim = np.sqrt(3.0 / sizes[i])          # lecun-uniform, brax's default
        w = rng.uniform(-lim, lim, (sizes[i], sizes[i + 1])).astype(np.float32)
        b = rng.uniform(-0.1, 0.1, sizes[i + 1]).astype(np.float32)
        layers.append((w, b))

    # -- forward pass, in float32 throughout to match the firmware ----------
    def forward(o):
        x = ((o - mean) / std).astype(np.float32)
        for i, (w, b) in enumerate(layers):
            x = (x @ w + b).astype(np.float32)
            if i + 1 < len(layers):
                x = swish(x).astype(np.float32)
        return np.tanh(x[:act_dim]).astype(np.float32)

    cases = []
    for k in range(6):
        o = (np.zeros(obs_dim, np.float32) if k == 0
             else rng.normal(0.0, 1.0, obs_dim).astype(np.float32) * (1 + k))
        cases.append((o, forward(o)))

    # -- weights header ----------------------------------------------------
    L = []
    w = L.append
    w("// GENERATED by tools/gen_policy_weights.py -- do not edit.")
    w("//")
    w("// *** PLACEHOLDER WEIGHTS -- NOT THE TRAINED POLICY. ***")
    w("// Correct input/output widths and correct brax semantics (swish")
    w("// hidden layers, 2*act_dim linear output, tanh mode), pseudo-random")
    w("// numbers. sim/export_policy.py replaces this file with the real")
    w("// distilled net; see firmware/README.md 'what is real in v1'.")
    w("#pragma once")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    w('#include "policy/dense.h"')
    w("")
    w("namespace policy {")
    w("")
    w("inline constexpr bool kWeightsArePlaceholder = true;")
    w("inline constexpr int kObsDim = %d;" % obs_dim)
    w("inline constexpr int kActDim = %d;" % act_dim)
    w("inline constexpr int kNumLayers = %d;" % len(layers))
    w("inline constexpr int kMaxWidth = %d;"
      % max([obs_dim] + [s for s in sizes[1:]]))
    w("")
    w("// running_statistics.normalize: x = (obs - mean) / std")
    L += carr("kNormMean", mean)
    L += carr("kNormStd", std)
    w("")
    for i, (wt, b) in enumerate(layers):
        w("// layer %d: (%d, %d), flax kernel order (in, out) row-major"
          % (i, wt.shape[0], wt.shape[1]))
        L += carr("kW%d" % i, wt, per_line=8)
        L += carr("kB%d" % i, b, per_line=8)
        w("")
    w("inline constexpr Dense kLayers[kNumLayers] = {")
    for i, (wt, b) in enumerate(layers):
        w("    {%d, %d, kW%d, kB%d}," % (wt.shape[0], wt.shape[1], i, i))
    w("};")
    w("")
    w("}  // namespace policy")
    w("")
    os.makedirs(os.path.dirname(WEIGHTS_OUT), exist_ok=True)
    with open(WEIGHTS_OUT, "w") as f:
        f.write("\n".join(L))

    # -- golden vectors ----------------------------------------------------
    V = []
    v = V.append
    v("// GENERATED by tools/gen_policy_weights.py -- do not edit.")
    v("// numpy-computed obs -> action for the placeholder net in weights.h.")
    v("#pragma once")
    v("#include <stddef.h>")
    v("")
    v("namespace policy_vectors {")
    v("")
    v("inline constexpr int kObsDim = %d;" % obs_dim)
    v("inline constexpr int kActDim = %d;" % act_dim)
    v("")
    v("struct Case { float obs[kObsDim]; float action[kActDim]; };")
    v("inline const Case kCases[] = {")
    for o, a in cases:
        v("    {{" + ", ".join(fl(x) for x in o) + "},")
        v("     {" + ", ".join(fl(x) for x in a) + "}},")
    v("};")
    v("inline constexpr size_t kNumCases = sizeof kCases / sizeof kCases[0];")
    v("")
    v("}  // namespace policy_vectors")
    v("")
    os.makedirs(os.path.dirname(VEC_OUT), exist_ok=True)
    with open(VEC_OUT, "w") as f:
        f.write("\n".join(V))

    nparams = sum(w_.size + b.size for w_, b in layers) + 2 * obs_dim
    print("placeholder net: %s -> %s (%d params, %.1f KB fp32)"
          % (obs_dim, " -> ".join(str(s) for s in sizes[1:]), nparams,
             nparams * 4 / 1024.0))
    print("wrote %s" % WEIGHTS_OUT)
    print("wrote %s (%d cases)" % (VEC_OUT, len(cases)))


if __name__ == "__main__":
    main()
